apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: cloudevents-player
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ruromero/cloudevents-player-jdk8:latest