apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: cloudevents-player
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: cloudevents-player